version: "3.9"
services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - sbs_db_vol:/data/db
    networks:
      - sbs_net

networks:
  sbs_net:
    name: sbs_net
    driver: bridge

volumes:
  sbs_db_vol:
